### ISSUE TITLE
[FEATURE REQUEST] Populate available resource names in dropdown

### ISSUE THREAD

**Issue by Lazytron** [bmarian/token-tooltip-alt#46]
**Is your feature request related to a problem? Please describe.**
Currently adding basic items to the tooltip require a RTFM, turning this field into a dropdown and leaving the "exp" flag for the advanced version would make it much easier for most folks to drop right into.

**Describe the solution you'd like**
I feel the name field should populate as a dropdown of values (much like the token UI) in the default state, and only change to a free-text field if the expression flag is checked. Ideally this would render any selected dropdown item into that free text field if it was already selected and the exp flag becomes checked, and if there is only a field name, re-select that in the dropdown if exp is unchecked.

**Describe alternatives you've considered**
n/a

**Additional context**
Just another nice to have. I think would help smooth the learning curve for folks who are hanging on by their fingernails to understand all the tech that gets dropped in the Foundry community...=)

**Comment by bmarian** [comment]
This is pretty hard to do.

Small tech talk: Those values are populated from the token's data structure. Witch is available because you can get to that menu only from the token/actor. In my case, you have that menu inside the settings menu you can open it without ever touching a token. So you can get a nice view of an empty dropdown.

I will explore some options. But don't hold your breath for this.

**Comment by bmarian** [comment]
Just checked this out in other systems. The data you can access depends on the token type. And they can have very different structures. 

So it makes it even more useless.
